### ISSUE TITLE
stammtisch erwähnen

### ISSUE THREAD

**Issue by datendelphin** [sosm/osm-ch-website#12]
der zürcher stammtisch, und vielleicht auch andere inaktive stammtische erwähnen unter Hilfe/Kontakt

**Comment by LoremoCH** [comment]
How about just integrate osmcal.org with a filter for Switzerland?

**Comment by datendelphin** [comment]
sounds good. Only draw back is, that we need to keep osmcal up to date :)

**Comment by sfkeller** [comment]
Ich würde den Vorschlag zur Integration von osmcal in einen separaten Issue tun.

**Comment by sfkeller** [comment]
> der zürcher stammtisch, und vielleicht auch andere inaktive stammtische erwähnen unter Hilfe/Kontakt

Hier ein Vorschlag - was meint ihr dazu?

### Events

Es finden immer wieder Events rund um OpenStreetMap statt, wie namentlich der monatliche [Zürcher Stammtisch (OSM-Treffen in Zürich)](https://wiki.openstreetmap.org/wiki/DE:Switzerland:Z%C3%BCrich/OSM-Treffen). Weitere Events finden sich im [OpenStreetMap-Kalender (osmcal)](https://osmcal.org/?in=Switzerland) .

**Comment by datendelphin** [comment]
deployed
