### ISSUE TITLE
Twitter bei "Hilfe" erwähnen

### ISSUE THREAD

**Issue by sfkeller** [sosm/osm-ch-website#13]
Auf osm.ch/hilfe.html sollte Twitter @SwissOSM https://twitter.com/SwissOSM erwähnt werden.

**Comment by Piagno** [comment]
Hast du oder sonst jemand einen Vorschlag welchen Text dazu geschrieben werden kann?
Nur ein Link, wäre wohl ein bisschen wenig.

**Comment by sfkeller** [comment]
Ok. Hier mein Vorschlag - ev. grad nach "Forum":

````
Social Media 

More and more peopla are using social media to distribute news. Unregistered 
users can at least read tweets. The Swiss OpenStreetMap Association can be 
followed and reached on the Twitter account @SwissOSM[http://twitter.com/SwissOSM].
````

@simonpoole bitte das English noch prüfen.

**Comment by simonpoole** [comment]
> Unregistered users can at least read it without being logged in.

Würde ich ganz weglasse, falls nicht, dann eher "Everybody can read such sources, most without being logged in."

**Comment by Piagno** [comment]
Super, Übersetzung ist auch vorhanden!
Kann geschlossen werden.
