### ISSUE TITLE
Link correction

### ISSUE THREAD

**Issue by lukasschnellmann** [sosm/osm-ch-website#25]
Change this link `<a href="https://md.coredump.ch/s/M3HuJuPJi#)">Tutorial</a>`
to `<a href="https://md.coredump.ch/s/S17YgVfzX">Tutorial</a>`

**Comment by sfkeller** [comment]
Seems already merged https://github.com/sosm/osm-ch-website/pull/24/files but not yet deployed.

**Comment by datendelphin** [comment]
deployed
